"""AD-1195: which EventType members events.db can answer for.

A stdlib-only leaf keyed by member NAME, so ``EventType``, its values, ``str``
equality and pickling stay untouched. It must not import ``probos.events``:
``probos.events`` calls ``assert_complete`` with its member names right after
the class, so the import fails while a member is neither declared nor in the
``GRANDFATHERED`` snapshot.

A DURABLE member is recorded one of two ways. ``DurableEventRouter`` writes it
as a ``(ROUTED_CATEGORY, <value>)`` row, or an existing OWNER already writes
its own row (``OWNER_RECORDS``). The router skips owner members, so those rows
are never doubled.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from enum import Enum
from types import MappingProxyType
from typing import Final


class Persistence(str, Enum):
    """How far events.db can answer for an EventType member."""

    DURABLE = "durable"
    """Persisted: absence within retention is evidence."""
    OPERATIONAL = "operational"
    """Live dispatch only: never persisted by the router."""
    DIAGNOSTIC = "diagnostic"
    """Best effort: absence is never evidence."""


class EventPersistenceContractError(RuntimeError):
    """The EventType members and these tables disagree; raised when ``probos.events`` imports."""


ROUTED_CATEGORY: Final = "event_type"
"""The events.db category of every row the router writes."""

DROP_MARKER_EVENT: Final = "durable_event_dropped"
"""The event of the one row the router writes per overflow episode."""

_DURABLE = Persistence.DURABLE
_OPERATIONAL = Persistence.OPERATIONAL

DECLARATIONS: Mapping[str, Persistence] = MappingProxyType({
    # Governance: requests, denials and interventions.
    "CAPABILITY_REQUEST_FILED": _DURABLE,
    "CAPABILITY_REQUEST_DECIDED": _DURABLE,
    "CAPABILITY_REQUEST_FULFILLED": _DURABLE,
    "TOOL_PERMISSION_DENIED": _DURABLE,
    "TOOL_INTERVENTION_REQUIRED": _DURABLE,
    # The ship changing itself.
    "SELF_MOD_STARTED": _DURABLE,
    "SELF_MOD_IMPORT_APPROVED": _DURABLE,
    "SELF_MOD_SUCCESS": _DURABLE,
    "SELF_MOD_FAILURE": _DURABLE,
    "DESIGN_GENERATED": _DURABLE,
    "SHIP_NAMED": _DURABLE,
    # Security controls deciding.
    "THREAT_DETECTED": _DURABLE,
    "TRUST_INTEGRITY_VIOLATION": _DURABLE,
    "SECURITY_INPUT_REJECTED": _DURABLE,
    "EGRESS_BLOCKED": _DURABLE,
    "BOUNDARY_VIOLATION_DETECTED": _DURABLE,
    "CLASSIFICATION_DISCLOSURE_BLOCKED": _DURABLE,
    "CREDENTIAL_READ": _DURABLE,
    "CREDENTIAL_READ_DENIED": _DURABLE,
    "SECRET_ROTATED": _DURABLE,
    "CREDENTIAL_TIER_DENIED": _DURABLE,
    # Execution.
    "MCP_BRIDGE_INVOKE": _DURABLE,
    "MCP_BRIDGE_FAILED": _DURABLE,
    # Durable state.
    "WORK_ITEM_STATUS_CHANGED": _DURABLE,
    "WORK_ITEM_QUARANTINED": _DURABLE,
    "CREW_TASK_STARTED": _DURABLE,
    "CREW_TASK_COMPLETED": _DURABLE,
    "CONFIG_CHANGED": _DURABLE,
    # Written by an owner, so the router skips them (OWNER_RECORDS).
    "CONSENSUS": _DURABLE,
    "AGENT_WIRED": _DURABLE,
    "AGENT_SELF_NAMED": _DURABLE,
    "TOOL_INVOKED": _DURABLE,
    "TOOL_STARTED": _DURABLE,
    "TOOL_RECORD_BUDGET_EXHAUSTED": _DURABLE,
    "BACKUP_COMPLETE": _DURABLE,
    "BACKUP_FAILED": _DURABLE,
    # OPERATIONAL: live dispatch only; the router never writes them (Q6).
    "AGENTIC_TOOL_CALL_STARTED": _OPERATIONAL,
    "AGENTIC_TOOL_CALL_COMPLETED": _OPERATIONAL,
    "AUDIT_RECORDED": _OPERATIONAL,
    "AUDIT_PERSISTED": _OPERATIONAL,
})
"""Members whose persistence class is declared, by NAME."""

OWNER_RECORDS: Mapping[str, tuple[str, str]] = MappingProxyType({
    "CONSENSUS": ("consensus", "quorum_evaluated"),
    "AGENT_WIRED": ("lifecycle", "agent_wired"),
    "AGENT_SELF_NAMED": ("naming", "agent_self_named"),
    "TOOL_INVOKED": ("tool", "tool_invoked"),
    "TOOL_STARTED": ("tool", "tool_started"),
    "TOOL_RECORD_BUDGET_EXHAUSTED": ("tool", "tool_record_budget_exhausted"),
    "BACKUP_COMPLETE": ("backup", "backup_complete"),
    "BACKUP_FAILED": ("backup", "backup_failed"),
})
"""DURABLE members an existing owner already writes, to the ``(category, event)`` it writes."""

# AD-1195 snapshot: may only shrink (promotion).
GRANDFATHERED: frozenset[str] = frozenset({
    "ACTION_RISK_DENIED",
    "AGENTIC_LOOP_ITERATION",
    "AGENT_CAPACITY_APPROACHING",
    "AGENT_REMOVED",
    "AGENT_STATE",
    "AGENT_VERSION_PROMOTED",
    "ANOMALY_WINDOW_CLOSED",
    "ANOMALY_WINDOW_OPENED",
    "APPEARANCE_REVISION_MEDIATED",
    "ARTIFACT_VERSION_ADDED",
    "ASSIGNMENT_COMPLETED",
    "ASSIGNMENT_CREATED",
    "ASSIGNMENT_UPDATED",
    "ATTACHMENT_REAPED",
    "ATTACHMENT_STORE_DISK_FULL",
    "BEHAVIORAL_METRICS_UPDATED",
    "BILLET_ASSIGNED",
    "BILLET_VACATED",
    "BILL_ACTIVATED",
    "BILL_CANCELLED",
    "BILL_COMPLETED",
    "BILL_FAILED",
    "BILL_ROLE_ASSIGNED",
    "BILL_STEP_COMPLETED",
    "BILL_STEP_FAILED",
    "BILL_STEP_STARTED",
    "BOOKING_CANCELLED",
    "BOOKING_COMPLETED",
    "BOOKING_STARTED",
    "BOOT_CAMP_ACTIVATED",
    "BOOT_CAMP_GRADUATION",
    "BOOT_CAMP_PHASE_ADVANCE",
    "BOOT_CAMP_PHASE_ADVANCED",
    "BOOT_CAMP_TIMEOUT",
    "BRIDGE_ALERT",
    "BROWSER_ACTION_EXECUTED",
    "BROWSER_BRIDGE_CONNECTED",
    "BROWSER_BRIDGE_DISCONNECTED",
    "BROWSER_BRIDGE_REFUSED",
    "BROWSER_COMPUTE_USE_CLICK_ABORTED",
    "BROWSER_COMPUTE_USE_CLICK_EXECUTED",
    "BROWSER_COMPUTE_USE_CLICK_PROPOSED",
    "BROWSER_COMPUTE_USE_CLICK_VERIFIED",
    "BROWSER_DOWNLOAD_REQUESTED",
    "BROWSER_EVAL_JS_EXECUTED",
    "BROWSER_FILE_UPLOAD_REQUESTED",
    "BROWSER_INPUT_FORWARDED",
    "BROWSER_INPUT_REFUSED",
    "BROWSER_RECORDING_EXPIRED",
    "BROWSER_RECORDING_FAILED",
    "BROWSER_RECORDING_STARTED",
    "BROWSER_RECORDING_STOPPED",
    "BROWSER_SESSION_CLOSED",
    "BROWSER_SESSION_OPENED",
    "BROWSER_STREAM_CLOSED",
    "BROWSER_STREAM_FRAME_DROPPED",
    "BROWSER_STREAM_OPENED",
    "BROWSER_VERIFY_OBSERVED",
    "BUILD_FAILURE",
    "BUILD_GENERATED",
    "BUILD_PROGRESS",
    "BUILD_QUEUE_ITEM",
    "BUILD_QUEUE_UPDATE",
    "BUILD_RESOLVED",
    "BUILD_STARTED",
    "BUILD_SUCCESS",
    "CAPABILITY_ACCESS_RESOLVED",
    "CAPABILITY_CONFIDENCE_UPDATED",
    "CAPABILITY_GAP_PREDICTED",
    "CAPABILITY_PROPOSAL_APPROVED",
    "CAPABILITY_PROPOSAL_CREATED",
    "CAPABILITY_PROPOSAL_REJECTED",
    "CAPTAINS_LOG_GENERATED",
    "CAPTAIN_DM_PRIORITY_QUEUED",
    "CASCADE_CONFABULATION_DETECTED",
    "CHANNEL_DELIVERY_FAILED",
    "CHANNEL_MESSAGE_RECEIVED",
    "CHAT_THREAD_MESSAGE_APPENDED",
    "CIRCUIT_BREAKER_TRIP",
    "COMMITMENT_RECORDED",
    "COMPENSATION_TRIGGERED",
    "CONDUCT_VIOLATION",
    "CONFABULATION_SUPPRESSED",
    "CONSULTATION_COMPLETED",
    "CONSULTATION_FAILED",
    "CONSULTATION_REQUESTED",
    "CONSULTATION_TIMEOUT",
    "CONTENT_CONTAGION_FLAGGED",
    "CONTENT_QUARANTINE_RECOMMENDED",
    "CONTEXT_PROVENANCE_INJECTED",
    "CONTRASTIVE_RECALL",
    "CONVERGENCE_DETECTED",
    "CORROBORATION_PROVENANCE_VALIDATED",
    "CORROBORATION_VERIFIED",
    "COUNSELOR_ASSESSMENT",
    "COUNSELOR_INTERVENTION",
    "CREATIVE_SKILL_AFFINITY_QUERIED",
    "CREATIVE_WORK_PUBLISHED",
    "CREDENTIAL_DELETED",
    "CREDENTIAL_FILL_REQUESTED",
    "CREDENTIAL_STORED",
    "CREW_ORCHESTRATION_STARTED",
    "CROSS_AGENT_DIVERGENCE_OBSERVED",
    "CURRICULUM_MODULE_QUERIED",
    "DAMAGE_CONTROL_ACTIVATED",
    "DECISION_QUEUE_PAUSED",
    "DECOMPOSE_COMPLETE",
    "DECOMPOSE_START",
    "DELIBERATION_ARGUMENT_SUBMITTED",
    "DELIBERATION_INITIATED",
    "DELIBERATION_RESOLVED",
    "DEPT_PROFILE_APPLIED",
    "DESIGN_FAILURE",
    "DESIGN_PROGRESS",
    "DESIGN_STARTED",
    "DISCLOSURE_FILTERED",
    "DISCOVERY_OUTCOME_RECORDED",
    "DISCOVERY_SCENARIO_OFFERED",
    "DIVERGENCE_DETECTED",
    "DIVERGENCE_OBSERVED_CHAIN",
    "DM_CONVERGENCE_DETECTED",
    "DREAM_COMPLETE",
    "DREAM_MANIFEST_UPDATED",
    "DUTY_SCOPE_QUERIED",
    "EMERGENCE_METRICS_UPDATED",
    "ENGINEERING_SENSOR_REPORT",
    "EPISODE_REJECTED",
    "EPS_BUDGET_EXCEEDED",
    "EPS_REALLOCATION",
    "ESCALATION_EXHAUSTED",
    "ESCALATION_RESOLVED",
    "ESCALATION_START",
    "EVOLUTION_LESSON_RECORDED",
    "EXOGENOUS_ALERT",
    "EXOGENOUS_CONSENSUS",
    "EXOGENOUS_GOSSIP",
    "EXOGENOUS_MENTION",
    "EXOGENOUS_SAFETY",
    "EXOGENOUS_SCENE_CHANGE",
    "FAULT_REPORTED",
    "FAULT_RESOLVED",
    "FEDERATION_DESIGNED_AGENT_RECEIVED",
    "FEDERATION_EPISODE_REJECTED",
    "FEDERATION_PEER_DISCOVERED",
    "FEDERATION_PEER_RECOVERED",
    "FEDERATION_PEER_UNREACHABLE",
    "FEDERATION_RECALL_DP_REDACTED",
    "FLEET_GAP_SNAPSHOT_TAKEN",
    "FORCED_CONSOLIDATION_TRIGGERED",
    "FRAGMENTATION_WARNING",
    "GAME_COMPLETED",
    "GAME_PREFERENCE_RECORDED",
    "GAME_UPDATE",
    "GAP_IDENTIFIED",
    "GAP_REMEDIATION_RECORDED",
    "GROUPTHINK_WARNING",
    "HEBBIAN_UPDATE",
    "HOLODECK_AFFECTIVE_BASELINE_OBSERVED",
    "HOLODECK_AGENT_ADMITTED",
    "HOLODECK_GRADUATION",
    "HOLODECK_PHASE_ENTERED",
    "HOLODECK_PHASE_GATE_BLOCKED",
    "HOLODECK_PHASE_GATE_PASSED",
    "HOLODECK_SCENARIO_GAP_LINKED",
    "HOLODECK_SCENARIO_GENERATED",
    "HOLODECK_SCENARIO_OUTCOME_RECORDED",
    "HOLODECK_SCENARIO_REGISTERED",
    "HYBRID_DISPATCH_BROADCAST",
    "HYBRID_DISPATCH_DIRECT",
    "IDEA_CAPTURED",
    "INFODYNAMIC_REPORT",
    "INITIATIVE_PROPOSAL",
    "KNOWLEDGE_CONFIRMED",
    "KNOWLEDGE_CONTRADICTED",
    "KNOWLEDGE_PINNED",
    "KNOWLEDGE_TIER_LOADED",
    "KNOWLEDGE_UNPINNED",
    "LEADERSHIP_DIVERGENCE",
    "LEARNED_SHORTCUT_HIT",
    "LEARNED_SHORTCUT_REGISTERED",
    "LIMDU_RECOMMENDED",
    "LLM_HEALTH_CHANGED",
    "MAINTENANCE_SCHEDULED",
    "MCP_APP_EXTERNAL_DISCOVERED",
    "MCP_APP_RESOURCE_READ",
    "MCP_APP_TOOL_INVOKED",
    "MCP_APP_TOOL_REGISTERED",
    "MEMORY_ANCHOR_MISMATCH",
    "MEMORY_INJECTION_SUSPECTED",
    "MEMORY_LEAK_SUSPECTED",
    "MEMORY_PROVENANCE_GAP",
    "MEMORY_RECALL_ANOMALY",
    "MEMORY_REFS_DISPATCHED",
    "MODEL_FALLBACK",
    "MODEL_ROUTED",
    "NODE_COMPLETE",
    "NODE_FAILED",
    "NODE_START",
    "NOTEBOOK_QUALITY_UPDATED",
    "NOTEBOOK_SELF_REPETITION",
    "NOTIFICATION",
    "NOTIFICATION_ACK",
    "NOTIFICATION_SNAPSHOT",
    "OBSERVABILITY_BRIDGE_FAILED",
    "OBSERVABILITY_SNAPSHOT_PUBLISHED",
    "OBSERVABLE_STATE_MISMATCH",
    "ONTOLOGY_PROBE_RATE_LIMITED",
    "ONTOLOGY_PROBE_RECORDED",
    "OPTIMIZATION_PROPOSAL_APPLIED",
    "OPTIMIZATION_PROPOSAL_REVERTED",
    "OPTIMIZATION_REGRESSION_DETECTED",
    "ORACLE_LOOKUP_DISPATCHED",
    "ORDER_ACKNOWLEDGED",
    "ORDER_DECLINED",
    "ORDER_ISSUED",
    "ORDER_REFUSED",
    "ORDER_REJECTED",
    "OS_ACTIVITY",
    "PAIRING_APPROVED",
    "PAIRING_REQUESTED",
    "PAIRING_REVOKED",
    "PARALLEL_DISPATCH_BLOCKED",
    "PARALLEL_DISPATCH_PROGRESS",
    "PARALLEL_DISPATCH_STARTED",
    "PEER_OBSERVATION_CERTIFICATION_REVOKED",
    "PEER_OBSERVATION_CERTIFIED",
    "PEER_OBSERVATION_DECLINED",
    "PEER_OBSERVATION_INTERVENTION_TIER_1",
    "PEER_OBSERVATION_INTERVENTION_TIER_2",
    "PEER_OBSERVATION_INTERVENTION_TIER_3",
    "PEER_OBSERVATION_PATTERN_FLAGGED",
    "PEER_OBSERVATION_PERMISSION_DENIED",
    "PEER_OBSERVATION_PERMISSION_GRANTED",
    "PEER_OBSERVATION_PERMISSION_REQUESTED",
    "PEER_OBSERVATION_RECORDED",
    "PEER_REPETITION_DETECTED",
    "PERFORMANCE_THRESHOLD_BREACHED",
    "PIVOT_REFINE_DECIDED",
    "PLAN_OF_DAY_GENERATED",
    "PREDICTION_ERROR_RECORDED",
    "PREDICTION_FLUSHED",
    "PREDICTION_HIT",
    "PREDICTION_MISS",
    "PREFLIGHT_FAILED",
    "PROACTIVE_THOUGHT",
    "PROCEDURE_FALLBACK_LEARNING",
    "QUALIFICATION_BASELINE_SET",
    "QUALIFICATION_DRIFT_DETECTED",
    "QUALIFICATION_GATE_BLOCKED",
    "QUALIFICATION_TEST_COMPLETE",
    "QUALITY_CONCERN",
    "QUEUE_ITEM_DEQUEUED",
    "QUEUE_ITEM_ENQUEUED",
    "QUEUE_ITEM_SHED",
    "QUEUE_OVERFLOW",
    "READY_ROOM_SESSION_STARTED",
    "RECREATION_GAME_REGISTERED",
    "RECREATION_SPECTATOR_COMMENTARY",
    "RECREATION_SPECTATOR_JOINED",
    "RED_TEAM_CAMPAIGN_COMPLETE",
    "REGISTER_SHIFT_DENIED",
    "REGISTER_SHIFT_GRANTED",
    "REMINISCENCE_SESSION_COMPLETE",
    "RENDER_DIVERGENCE_OBSERVED",
    "RESOURCE_ALLOCATED",
    "RETRIEVAL_PRACTICE_CONCERN",
    "SANDBOX_CAPABILITY_DENIED",
    "SANDBOX_LIMIT_EXCEEDED",
    "SCHEDULED_TASK_CANCELLED",
    "SCHEDULED_TASK_CREATED",
    "SCHEDULED_TASK_DAG_RESUMED",
    "SCHEDULED_TASK_DAG_STALE",
    "SCHEDULED_TASK_FIRED",
    "SCHEDULED_TASK_UPDATED",
    "SELF_MODEL_DRIFT",
    "SELF_MOD_PROGRESS",
    "SELF_MOD_RETRY_COMPLETE",
    "SELF_MONITORING_CONCERN",
    "SELF_RENDER_COHERENCE_OBSERVED",
    "SENSORIUM_BUDGET_EXCEEDED",
    "SERVICE_TIER_DEGRADED",
    "SERVICE_TIER_RESTORED",
    "SHIP_STATE_SNAPSHOT_CAPTURED",
    "SKILL_ACQUIRED",
    "SKILL_BLOCKED",
    "SKILL_DECAY",
    "SKILL_EXERCISED",
    "SKILL_LOADED",
    "SKILL_REGRESSION",
    "SKILL_REQUEST_COMPLETED",
    "SKILL_REQUEST_DECIDED",
    "SKILL_REQUEST_FILED",
    "SKILL_REQUEST_TRAINING_STARTED",
    "SPC_RULE_VIOLATED",
    "STRENGTH_MAP_UPDATED",
    "SUBSYSTEM_PAUSED",
    "SUBSYSTEM_RESUMED",
    "SUBTASK_COMPLETED",
    "SUB_TASK_CHAIN_COMPLETED",
    "SUB_TASK_COMPLETED",
    "SYSTEM_MODE",
    "TASK_CREATED",
    "TASK_EVENT_DISPATCHED",
    "TASK_EVENT_UNROUTABLE",
    "TASK_EXECUTION_COMPLETE",
    "TASK_ROUTED",
    "TASK_SCHEDULED",
    "TASK_UPDATED",
    "TEAM_SCENARIO_REGISTERED",
    "TEAM_SIMULATION_COMMUNICATION_CONSTRAINT_APPLIED",
    "TEAM_SIMULATION_COMPLETED",
    "TEAM_SIMULATION_DEBRIEF_RECORDED",
    "TEAM_SIMULATION_ROLE_ROTATED",
    "TEAM_SIMULATION_STARTED",
    "TELEMETRY_REPORT",
    "THREAD_PRIORITY_SCORED",
    "TIERED_TRUST_INITIALIZED",
    "TOOL_CONTEXT_CREATED",
    "TOOL_FAILURE_PATTERN",
    "TOOL_LOCKED",
    "TOOL_UNLOCKED",
    "TRANSPORTER_ASSEMBLED",
    "TRANSPORTER_CHUNK_DONE",
    "TRANSPORTER_DECOMPOSED",
    "TRANSPORTER_EXECUTION_DONE",
    "TRANSPORTER_VALIDATED",
    "TRANSPORTER_WAVE_START",
    "TRUST_CASCADE_WARNING",
    "TRUST_UPDATE",
    "VALIDATION_OUTCOME_VERIFIED",
    "VALIDATION_RECONCILIATION_REQUESTED",
    "VERIFICATION_FAILED",
    "VERIFICATION_PASSED",
    "VERIFICATION_REJECTED",
    "VISION_CAPABILITY_PROPOSED",
    "VISION_CAPABILITY_RESOLVED",
    "VISION_INTENT_DIVERGENCE_OBSERVED",
    "WARD_ROOM_ECHO_DETECTED",
    "WARD_ROOM_ENDORSEMENT",
    "WARD_ROOM_HEBBIAN_DECAYED",
    "WARD_ROOM_HEBBIAN_UPDATED",
    "WARD_ROOM_POST_CREATED",
    "WARD_ROOM_PRUNED",
    "WARD_ROOM_THREAD_CREATED",
    "WARD_ROOM_THREAD_UPDATED",
    "WORKFLOW_STARTED",
    "WORKING_MEMORY_NOTE_RECORDED",
    "WORKSPACE_TERM_REGISTERED",
    "WORK_ITEM_ASSIGNED",
    "WORK_ITEM_CLAIMED",
    "WORK_ITEM_CREATED",
    "WORK_ITEM_RECONCILED",
    "WORK_ITEM_UPDATED",
    "WRONG_CONVERGENCE_DETECTED",
    "ZONE_RECOVERY",
    "ZPD_SCENARIO_CALIBRATED",
})
"""Members with no declared class, frozen at AD-1195. A name leaves when it is declared or its member is removed."""


def persistence_of(name: str) -> Persistence | None:
    """The declared class of member ``name``, or None when it is not declared."""
    return DECLARATIONS.get(name)


def is_routed(name: str) -> bool:
    """True when the router writes member ``name``: DURABLE and not owner-written."""
    return DECLARATIONS.get(name) is Persistence.DURABLE and name not in OWNER_RECORDS


def durable_record_key(name: str, value: str) -> tuple[str, str] | None:
    """The ``(category, event)`` row that records DURABLE member ``name``, else None."""
    if DECLARATIONS.get(name) is not Persistence.DURABLE:
        return None
    return OWNER_RECORDS.get(name, (ROUTED_CATEGORY, value))


def assert_complete(member_names: Iterable[str]) -> None:
    """Raise unless every member is declared or grandfathered and every table names only members.

    Reads ``DECLARATIONS``, ``GRANDFATHERED`` and ``OWNER_RECORDS`` when called.
    Each kind of problem is listed with its names sorted and a remedy line.
    """
    members = set(member_names)
    declared = set(DECLARATIONS)
    checks = (
        ("undeclared (neither in DECLARATIONS nor in GRANDFATHERED)", members - declared - GRANDFATHERED,
         "declare each in DECLARATIONS; a new member is never added to GRANDFATHERED"),
        ("in both DECLARATIONS and GRANDFATHERED", declared & GRANDFATHERED,
         "remove each from GRANDFATHERED: the snapshot only shrinks"),
        ("stale in DECLARATIONS (not an EventType member)", declared - members,
         "remove each from DECLARATIONS"),
        ("stale in GRANDFATHERED (not an EventType member)", GRANDFATHERED - members,
         "remove each from GRANDFATHERED"),
        ("stale in OWNER_RECORDS (not an EventType member)", set(OWNER_RECORDS) - members,
         "remove each from OWNER_RECORDS"),
        ("in OWNER_RECORDS but not declared DURABLE",
         {name for name in OWNER_RECORDS if DECLARATIONS.get(name) is not Persistence.DURABLE},
         "declare each DURABLE, or remove it from OWNER_RECORDS"),
    )
    problems = [
        f"- {kind}: {', '.join(sorted(names))}\n  remedy: {remedy}"
        for kind, names, remedy in checks
        if names
    ]
    if problems:
        raise EventPersistenceContractError(
            "AD-1195 event persistence contract (probos/event_persistence.py) is violated:\n"
            + "\n".join(problems)
        )
