"""AD-514: Service boundary protocols for interface segregation.

These protocols define the narrow interfaces that consumers depend on,
enabling decomposition of ProbOSRuntime into focused modules.
"""

from __future__ import annotations

from typing import Any, Callable, TYPE_CHECKING, Protocol, runtime_checkable

if TYPE_CHECKING:
    from probos.cognitive.self_mod import DesignedAgentRecord
    from probos.consensus.trust import TrustRecord
    from probos.ontology import VesselOntologyService
    from probos.types import Episode


@runtime_checkable
class EpisodicMemoryProtocol(Protocol):
    """What agents and services need from episodic memory."""

    async def store(self, episode: Episode) -> None: ...
    async def recall(self, query: str, k: int = 5) -> list[Episode]: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


@runtime_checkable
class TrustNetworkProtocol(Protocol):
    """What services need from the trust network."""

    def get_trust_score(self, agent_id: str) -> float: ...
    def get_or_create(self, agent_id: str) -> TrustRecord: ...
    def record_outcome(self, agent_id: str, success: bool, weight: float = 1.0) -> float: ...
    def remove_agent(self, agent_id: str) -> None: ...


@runtime_checkable
class EventLogProtocol(Protocol):
    """What services need from event logging."""

    async def log(self, category: str, agent_id: str, data: dict[str, Any] | None = None) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...


@runtime_checkable
class WardRoomProtocol(Protocol):
    """What services need from the Ward Room."""

    async def create_thread(self, channel_id: str, title: str, author_id: str, **kwargs: Any) -> dict[str, Any]: ...
    async def create_post(self, thread_id: str, author_id: str, content: str) -> dict[str, Any]: ...
    async def get_thread(self, thread_id: str) -> dict[str, Any] | None: ...
    async def list_channels(self) -> list[dict[str, Any]]: ...
    async def post_system_message(self, channel_name: str, content: str, author: str = "ship_computer") -> None: ...
    def set_ontology(self, ontology: VesselOntologyService) -> None: ...


@runtime_checkable
class KnowledgeStoreProtocol(Protocol):
    """What services need from the knowledge store."""

    async def store_agent(self, record: DesignedAgentRecord, source_code: str) -> None: ...
    async def store_episode(self, episode: Episode) -> None: ...
    async def store_skill(self, name: str, source: str, descriptor: dict[str, Any]) -> None: ...
    async def store_trust_snapshot(self, data: dict[str, Any]) -> None: ...
    async def store_routing_snapshot(self, data: dict[str, Any]) -> None: ...


@runtime_checkable
class HebbianRouterProtocol(Protocol):
    """What services need from Hebbian routing."""

    def record_interaction(self, source: str, target: str, success: bool) -> float: ...
    def get_all_weights(self) -> dict[tuple[str, str, str], float]: ...
    def set_weight(self, key: tuple[str, str, str], value: float) -> None: ...
    def remove_weights_for_agent(self, agent_id: str) -> None: ...


@runtime_checkable
class EventEmitterProtocol(Protocol):
    """What modules need to emit HXI events."""

    def emit_event(self, event_type: str, data: dict[str, Any]) -> None: ...
    def add_event_listener(self, fn: Callable[..., Any]) -> None: ...
    def remove_event_listener(self, fn: Callable[..., Any]) -> None: ...
