"""The reconciled AD/BF ledger must not drift, and its gate must not need a network.

``docs/development/open-ads-report.md`` is generated by
``scripts/gen_ad_ledger.py`` from four authorities. Two of them -- git history
and GitHub issues -- are captured into a pinned snapshot; the other two are
re-parsed on every run. This module is the forcing function: edit DECISIONS.md
or PROGRESS.md without regenerating and the suite goes red.

Fix a failure with::

    python scripts/gen_ad_ledger.py            # refresh the git layer
    python scripts/gen_ad_ledger.py --online   # ...and the issue layer

The load-bearing test here is ``test_check_opens_no_socket_and_spawns_no_process``.
The whole point of the generator is an authority that lives behind a network
call, and a gate that reaches for it would go red on a fork, offline, without a
token, or under rate limiting -- red for a reason unrelated to the code. So the
hermeticity is asserted rather than assumed.
"""

from __future__ import annotations

import importlib.util
import json
import re
import shutil
import socket
import subprocess
import sys
import types
from pathlib import Path

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
_SCRIPT = _REPO_ROOT / "scripts" / "gen_ad_ledger.py"
_REPORT = _REPO_ROOT / "docs" / "development" / "open-ads-report.md"
_SNAPSHOT = _REPO_ROOT / "docs" / "development" / "ad-ledger-snapshot.json"


@pytest.fixture(scope="module")
def ledger() -> types.ModuleType:
    """Import the generator from its path -- ``scripts/`` is not a package."""
    spec = importlib.util.spec_from_file_location("gen_ad_ledger", _SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _section(text: str, heading_prefix: str) -> str:
    """Return the body of the first ``## <heading_prefix>...`` section."""
    lines = text.splitlines()
    for index, line in enumerate(lines):
        if line.startswith("## ") and line[3:].startswith(heading_prefix):
            end = index + 1
            while end < len(lines) and not lines[end].startswith("## "):
                end += 1
            return "\n".join(lines[index:end])
    raise AssertionError(f"no section starting '## {heading_prefix}' in the report")


# --------------------------------------------------------------------------
# the artifact exists and is marked generated
# --------------------------------------------------------------------------


def test_the_generator_and_its_artifacts_are_committed() -> None:
    assert _SCRIPT.is_file(), "scripts/gen_ad_ledger.py is missing"
    assert _REPORT.is_file(), (
        "docs/development/open-ads-report.md is missing; run "
        "python scripts/gen_ad_ledger.py --online"
    )
    assert _SNAPSHOT.is_file(), (
        "the pinned snapshot is missing; --check cannot run offline without it"
    )


def test_the_report_is_marked_generated() -> None:
    """A reader who lands here from search must not hand-edit it."""
    text = _REPORT.read_text(encoding="utf-8")
    assert "do not edit by hand" in text.lower()
    assert "gen_ad_ledger.py" in text


# --------------------------------------------------------------------------
# 1. --check passes against the committed artifact
# --------------------------------------------------------------------------


def test_check_passes_against_the_committed_report() -> None:
    """Runs the real command a developer is told to run, not a reimplementation."""
    result = subprocess.run(
        [sys.executable, str(_SCRIPT), "--check"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=str(_REPO_ROOT),
        timeout=180,
    )
    assert result.returncode == 0, (
        "open-ads-report.md is stale.\n"
        "Regenerate with: python scripts/gen_ad_ledger.py\n\n"
        f"stdout: {result.stdout}\nstderr: {result.stderr}"
    )


# --------------------------------------------------------------------------
# 2. --check fails on a stale artifact
# --------------------------------------------------------------------------


def test_check_fails_when_the_report_is_stale(
    ledger: types.ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys
) -> None:
    """A mutated copy must be rejected -- otherwise the gate is decorative.

    The unmutated copy is checked first. Without that control a bug in this
    harness would look identical to a working gate.
    """
    report = tmp_path / "open-ads-report.md"
    snapshot = tmp_path / "ad-ledger-snapshot.json"
    shutil.copyfile(_REPORT, report)
    shutil.copyfile(_SNAPSHOT, snapshot)
    monkeypatch.setattr(ledger, "_OUTPUT", report)
    monkeypatch.setattr(ledger, "_SNAPSHOT", snapshot)

    assert ledger.main(["--check"]) == 0, "the unmutated copy should pass"

    report.write_text(
        report.read_text(encoding="utf-8").replace("AD-1202", "AD-1099", 1),
        encoding="utf-8",
    )
    assert ledger.main(["--check"]) == 1
    assert "STALE" in capsys.readouterr().err


def test_check_fails_when_the_report_is_absent(
    ledger: types.ModuleType, tmp_path: Path, monkeypatch: pytest.MonkeyPatch, capsys
) -> None:
    monkeypatch.setattr(ledger, "_OUTPUT", tmp_path / "nope.md")
    monkeypatch.setattr(ledger, "_SNAPSHOT", tmp_path / "nope.json")
    assert ledger.main(["--check"]) == 1
    assert "MISSING" in capsys.readouterr().err


# --------------------------------------------------------------------------
# 3. --check touches no network and no subprocess
# --------------------------------------------------------------------------


def test_check_opens_no_socket_and_spawns_no_process(
    ledger: types.ModuleType, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Asserted, not assumed -- this is the constraint the design turns on.

    Both are booby-trapped: a socket because the GitHub authority is a network
    call, and a subprocess because ``gh`` and ``git`` are how it would be
    reached. ``--check`` must resolve the pinned snapshot from disk instead.
    """
    reached: list[str] = []

    def _trap(name: str):
        def _fail(*_args: object, **_kwargs: object):
            reached.append(name)
            raise AssertionError(f"--check reached {name}; it must stay offline")

        return _fail

    for attr in ("socket", "create_connection", "getaddrinfo", "gethostbyname"):
        monkeypatch.setattr(socket, attr, _trap(f"socket.{attr}"))
    for attr in ("run", "Popen", "call", "check_output"):
        monkeypatch.setattr(subprocess, attr, _trap(f"subprocess.{attr}"))

    assert ledger.main(["--check"]) == 0
    assert reached == []


def test_check_and_online_are_mutually_exclusive(
    ledger: types.ModuleType, capsys
) -> None:
    """``--check --online`` must not quietly become a networked gate."""
    assert ledger.main(["--check", "--online"]) == 2
    assert "offline by design" in capsys.readouterr().err


# --------------------------------------------------------------------------
# 4/5. classification
# --------------------------------------------------------------------------


def test_an_open_issue_with_no_code_classifies_allocated_open(
    ledger: types.ModuleType,
) -> None:
    state, reason = ledger.classify(
        local=[],
        git_tokens=[],
        issues=[{"number": 4242, "state": "OPEN", "reason": "", "title": "AD-9999: x"}],
    )
    assert state == "allocated-open"
    assert "#4242" in reason


def test_a_number_no_authority_mentions_is_never_free(ledger: types.ModuleType) -> None:
    """The residual default is allocated, not free. That inference is the defect."""
    state, _ = ledger.classify(local=[], git_tokens=[], issues=[])
    assert state == "allocated-open"


def test_a_commit_outranks_an_open_issue(ledger: types.ModuleType) -> None:
    """Reality beats intent: code in history is shipped even if the issue is open."""
    state, _ = ledger.classify(
        local=[],
        git_tokens=["git AD-9999"],
        issues=[{"number": 1, "state": "OPEN", "reason": "", "title": "AD-9999: x"}],
    )
    assert state == "shipped"


def test_an_open_issue_outranks_a_deferred_tracker_line(
    ledger: types.ModuleType,
) -> None:
    """The precedence that makes AD-1152 ``allocated-open`` rather than deferred."""
    state, _ = ledger.classify(
        local=["PROGRESS.md:1 AD-9999 deferred"],
        git_tokens=[],
        issues=[{"number": 7, "state": "OPEN", "reason": "", "title": "AD-9999: x"}],
    )
    assert state == "allocated-open"


def test_a_not_planned_closure_with_no_code_is_retired(
    ledger: types.ModuleType,
) -> None:
    state, _ = ledger.classify(
        local=[],
        git_tokens=[],
        issues=[
            {"number": 9, "state": "CLOSED", "reason": "NOT_PLANNED", "title": "AD-9: x"}
        ],
    )
    assert state == "retired"


def test_ad_1152_classifies_allocated_open_not_free(ledger: types.ModuleType) -> None:
    """AD-1152 (#1079) is the canonical false-free number.

    It is open, titled as real unfinished work, and carries no retirement
    comment -- while `PROGRESS.md` line 9 still calls it the "next free" number
    and `DECISIONS.md` line 244 says work was "deferred to" it. A tree scan
    reads all of that as free. Verified twice: through the classifier against
    the real committed authorities, and in the published artifact.
    """
    local, _skipped, _sources = ledger.parse_local_authorities()
    snapshot = json.loads(_SNAPSHOT.read_text(encoding="utf-8"))
    issues = (snapshot.get("issues") or {}).get("issues") or {}
    git_tokens = (snapshot.get("git") or {}).get("tokens") or {}

    state, reason = ledger.classify(
        local=local.get("AD-1152", []),
        git_tokens=git_tokens.get("AD-1152", []),
        issues=issues.get("AD-1152", []),
    )
    assert state == "allocated-open", f"AD-1152 classified {state}: {reason}"
    assert "#1079" in reason

    published = _section(
        _REPORT.read_text(encoding="utf-8"), "Allocated and open"
    )
    assert "`AD-1152`" in published


# --------------------------------------------------------------------------
# 6. malformed entries are skipped and counted, not fatal
# --------------------------------------------------------------------------


def test_malformed_entries_are_skipped_and_counted(ledger: types.ModuleType) -> None:
    """One bad line must not abort a run over five eras of formatting.

    ``| AD | Decision |`` is a real markdown table header in
    ``progress-era-3-product.md``; it looks like an entry head and is not one.
    """
    found, skipped = ledger.parse_entry_lines(
        [
            "AD-9001 CLOSED. a well-formed entry",
            "AD- : no number at all",
            "BF-: also broken",
            "| AD | Decision |",
            "BF-9002 OPEN. another good one",
        ],
        source="synthetic.md",
        headings_only=False,
    )

    assert "AD-9001" in found and "BF-9002" in found
    assert len(skipped) == 3
    assert all("synthetic.md:" in entry for entry in skipped)


def test_the_real_authorities_report_their_skips(ledger: types.ModuleType) -> None:
    """Skips are surfaced, not swallowed -- a silent skip is a silent lie."""
    _local, skipped, sources = ledger.parse_local_authorities()
    assert sources, "no authority files were parsed"
    assert isinstance(skipped, list)
    assert "Unparseable lines" in _REPORT.read_text(encoding="utf-8")


# --------------------------------------------------------------------------
# 7. ceilings
# --------------------------------------------------------------------------


def test_derived_ceilings_clear_the_known_floor(ledger: types.ModuleType) -> None:
    """AD-1202 (#1142) and BF-712 (#1143) exist only as issues -- no code.

    A recursive tree scan reports AD-1180 / BF-706. If this assertion fails
    with a *lower* number, the issue layer has been lost and the generator is
    reproducing the defect it exists to prevent.
    """
    snapshot = json.loads(_SNAPSHOT.read_text(encoding="utf-8"))
    local, _skipped, _sources = ledger.parse_local_authorities()
    issues = (snapshot.get("issues") or {}).get("issues") or {}
    git_tokens = (snapshot.get("git") or {}).get("tokens") or {}

    ceilings: dict[str, int] = {}
    for key in set(local) | set(issues) | set(git_tokens):
        series, _, digits = key.partition("-")
        ceilings[series] = max(ceilings.get(series, 0), int(digits))

    assert ceilings["AD"] >= 1202, f"AD ceiling regressed to {ceilings['AD']}"
    assert ceilings["BF"] >= 712, f"BF ceiling regressed to {ceilings['BF']}"

    published = _section(_REPORT.read_text(encoding="utf-8"), "Ceilings")
    # Parse the numbers rather than matching a prefix.
    #
    # This read `"**AD-1202**" in published or "**AD-12" in published` and
    # `"**BF-712**" ... or "**BF-7"`, which silently encoded "BF is in the
    # 700s". The docstring says this must fail on a LOWER number; the prefix
    # form failed on a HIGHER one instead. It went red the moment the ceiling
    # reached BF-833 -- growth, which is the opposite of the regression it
    # exists to catch, and it would have taken the AD series with it at
    # AD-1300. Updated rather than deleted, so the change is recorded where
    # the old shape was.
    for series, floor in (("AD", 1202), ("BF", 712)):
        found = [int(n) for n in re.findall(rf"\*\*{series}-(\d+)\*\*", published)]
        assert found, f"the published Ceilings section names no {series} number"
        assert max(found) >= floor, (
            f"published {series} ceiling regressed to {max(found)}"
        )


def test_the_report_refuses_to_call_unmentioned_numbers_free() -> None:
    """The gap list must be labelled as silence, not as availability."""
    text = _REPORT.read_text(encoding="utf-8")
    assert "Unaccounted" in text
    assert "not** free" in text


# ---------------------------------------------------------------------------
# #1349 -- digit-suffixed slices were invisible, not mis-parsed
# ---------------------------------------------------------------------------

_CEILING_SCRIPT = _REPO_ROOT / "scripts" / "ad_ceiling.py"


@pytest.fixture(scope="module")
def ceiling() -> types.ModuleType:
    spec = importlib.util.spec_from_file_location("ad_ceiling", _CEILING_SCRIPT)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


@pytest.mark.parametrize(
    ("token", "expected"),
    [
        # The shapes that already worked must be byte-identical.
        ("AD-1270", ("AD", "1270", "")),
        ("AD-722b", ("AD", "722", "b")),
        ("BF-688a", ("BF", "688", "a")),
        ("AD-12345", ("AD", "12345", "")),
        # The shapes #1349 reported. `[a-z]{0,3}\b` cannot match these at all:
        # the suffix stops at `e` and the following digit is a word character,
        # so there is no boundary and the token was skipped entirely.
        ("AD-1270e1", ("AD", "1270", "e1")),
        ("AD-1270e2", ("AD", "1270", "e2")),
        ("AD-1270c3", ("AD", "1270", "c3")),
        # The same shape on the other branch of `(AD|BF)`. Every other
        # digit-suffixed row is AD, so a regression confined to BF would pass
        # unseen. Base 688 is the letter-only BF row above, which leaves the
        # trailing digit as the single difference between the two.
        ("BF-688a2", ("BF", "688", "a2")),
    ],
)
def test_the_ledger_token_parses_digit_suffixed_slices(
    ledger: types.ModuleType, token: str, expected: tuple[str, str, str]
) -> None:
    found = ledger._TOKEN_RE.findall(token)

    assert found == [expected], f"{token} parsed as {found}"


@pytest.mark.parametrize("token", ["AD-123456", "AD-1234567", "BF-123456"])
def test_a_digit_only_suffix_never_splits_a_long_number(
    ledger: types.ModuleType, ceiling: types.ModuleType, token: str
) -> None:
    """The suffix must start with a letter, or two numbers become one.

    An unconstrained ``\\d{0,2}`` tail read ``AD-123456`` as ``AD-12345`` with
    slice ``6`` -- measured -- while ``ad_ceiling`` rejected the same token
    outright. The ledger and the ceiling scanner would then disagree about
    which numbers exist, which is precisely what the ceiling is consulted for.
    """
    # Premise: both patterns are live on the nearest ACCEPTED neighbour -- the
    # same digits with a letter anchor. Without it a dead pattern would satisfy
    # the two rejections below, and an empty result proves nothing.
    assert ledger._TOKEN_RE.findall("AD-12345e6") == [("AD", "12345", "e6")]
    assert ceiling._AD_RE.findall("AD-12345e6") == ["12345"]

    assert ledger._TOKEN_RE.findall(token) == []
    # `_AD_RE` matches only the AD series, so this line is structurally empty
    # for the BF-123456 row -- that row is carried by the assertion above, not
    # by agreement between the two tools. It is not BF coverage.
    assert ceiling._AD_RE.findall(token) == []


def test_a_slice_is_keyed_on_its_base_number(ledger: types.ModuleType) -> None:
    """A slice is a child of its base, never a new allocation.

    This is the property that makes widening the suffix safe: ``AD-1270e2``
    must classify under 1270, so admitting it cannot invent a number.
    """
    _series, digits, suffix = ledger._TOKEN_RE.findall("AD-1270e2")[0]

    assert int(digits) == 1270
    assert suffix == "e2"


def test_the_entry_parser_keys_a_slice_under_its_base(
    ledger: types.ModuleType,
) -> None:
    """Through the real consumer, not the regex in isolation.

    ``_leading_tokens`` is what ``parse_entry_lines`` uses to decide which
    number an entry head governs. Asserting on the regex alone would not show
    that the slice reaches classification under 1270 with its full token kept
    as evidence.
    """
    head = "**AD-1270e2 shipped (2026-09-03) - batch 9**"

    assert ledger._leading_tokens(head) == [("AD", 1270, "AD-1270e2")]


def test_the_prompt_scanner_reads_a_digit_suffixed_filename(
    ceiling: types.ModuleType,
) -> None:
    """``_PROMPT_RE`` carried the same trailing-boundary defect.

    ``prompts/ad-1270e2-*.md`` exists in this repository, so without this the
    prompt authority silently contributed nothing for that slice.
    """
    assert ceiling._PROMPT_RE.findall("ad-1270e2-leaf-domain-config-extraction.md") == [
        "1270"
    ]
    assert ceiling._PROMPT_RE.findall("ad-1270-x.md") == ["1270"]
    assert ceiling._PROMPT_RE.findall("ad-123456-x.md") == []


def test_the_ceiling_scanner_sees_the_base_of_a_suffixed_token(
    ceiling: types.ModuleType,
) -> None:
    """A trailing ``\\b`` silently dropped every suffixed token, letters too.

    ``AD-722b`` was as invisible as ``AD-1270e2``; the reported gap was wider
    than #1349 described.
    """
    assert ceiling._AD_RE.findall("AD-1270e2") == ["1270"]
    assert ceiling._AD_RE.findall("AD-722b") == ["722"]
    assert ceiling._AD_RE.findall("AD-1270") == ["1270"]

    # A long number must not match a truncated prefix.
    assert ceiling._AD_RE.findall("AD-12345") == ["12345"]


def test_admitting_a_slice_does_not_raise_the_ceiling(
    ceiling: types.ModuleType,
) -> None:
    """The check #1349 asks for: the reported ceiling must not move.

    A corpus whose only mention of a number is a slice of it must yield that
    base number and nothing higher. The corpus deliberately contains no bare
    ``AD-1270``: with one, the old pattern found it anyway and this case passed
    against the defect it exists to catch.
    """
    corpus = "AD-1270e2 refines AD-1270e1; see also AD-722b."

    found = [int(n) for n in ceiling._AD_RE.findall(corpus)]

    # Premise: the old pattern really could not see these, so this is not a
    # comparison between two spellings of the same behaviour.
    assert re.compile(r"\bAD-(\d{1,5})\b").findall(corpus) == []

    assert found, "the scanner found nothing; it cannot be measuring a ceiling"
    assert max(found) == 1270
    assert 1271 not in found
