"""AD-1069: SkillForge — generate → validate → smoke-test → register.

Substrate-honest: a scripted LLM returns canned ``===FILE:`` blocks (a real
docx/xlsx/csv-generating skill), a REAL ``SubprocessSandbox`` runs the generated
script during the smoke-test, and a REAL ``CognitiveSkillCatalog`` registers the
result on disk. The headline test then runs the REGISTERED skill's script and
re-opens the produced ``.docx`` — proving the forge ships working skills, and
tying the AD-1065→1069 chain together (forge → register → run → real artifact).
"""

from __future__ import annotations

import io
from pathlib import Path

import pytest

from probos.cognitive.skill_catalog import CognitiveSkillCatalog
from probos.cognitive.skill_forge import SkillForge
from probos.execution.isolation import ExecutionRequest, SubprocessSandbox


# ── canned LLM output ─────────────────────────────────────────────────────
class _FakeLLMResponse:
    def __init__(self, content: str, error=None) -> None:
        self.content = content
        self.error = error


class _FakeLLM:
    """Returns a fixed completion — stands in for the deep-tier generator."""

    def __init__(self, content: str, error=None) -> None:
        self._content = content
        self._error = error
        self.last_request = None

    async def complete(self, request, **_kwargs):
        self.last_request = request
        return _FakeLLMResponse(self._content, self._error)


def _payload(name: str, script_body: str, *, description: str = "A forged test skill.") -> str:
    return (
        "===FILE: SKILL.md===\n"
        "---\n"
        f"name: {name}\n"
        f"description: {description}\n"
        "metadata:\n"
        '  probos-department: "*"\n'
        '  probos-min-rank: "ensign"\n'
        "  probos-activation: discovery\n"
        "---\n\n"
        f"# {name}\n\n"
        "Run scripts/generate.py to produce a sample. Edit CONFIG to customize.\n\n"
        "===FILE: scripts/generate.py===\n"
        f"{script_body}\n"
    )


_DOCX = (
    "from docx import Document\n"
    'CONFIG = {"title": "Sample Report", "body": "Generated by the ProbOS SkillForge."}\n'
    "doc = Document()\n"
    'doc.add_heading(CONFIG["title"], 0)\n'
    'doc.add_paragraph(CONFIG["body"])\n'
    'doc.save("output.docx")\n'
    'print("wrote output.docx")\n'
)

_XLSX = (
    "from openpyxl import Workbook\n"
    'CONFIG = {"rows": [["name", "score"], ["ezri", 9]]}\n'
    "wb = Workbook()\n"
    "ws = wb.active\n"
    'for row in CONFIG["rows"]:\n'
    "    ws.append(row)\n"
    'wb.save("output.xlsx")\n'
    'print("wrote output.xlsx")\n'
)

_CSV = (
    "import csv\n"
    'CONFIG = {"rows": [["name", "score"], ["ezri", "9"]]}\n'
    'with open("output.csv", "w", newline="", encoding="utf-8") as f:\n'
    '    csv.writer(f).writerows(CONFIG["rows"])\n'
    'print("wrote output.csv")\n'
)


async def _catalog(skills_root: Path) -> CognitiveSkillCatalog:
    skills_root.mkdir(parents=True, exist_ok=True)
    cat = CognitiveSkillCatalog(skills_dir=skills_root)
    await cat.start()
    return cat


# ── headline: forge a docx skill, then run the REGISTERED skill ────────────
async def test_forge_docx_skill_registers_and_runs(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM(_payload("docx-maker", _DOCX)), catalog=cat)

    result = await forge.forge(
        name="docx-maker",
        description="Create a Word document.",
        task="produce a .docx report",
    )

    assert result.success, result.errors
    assert result.name == "docx-maker"
    assert "output.docx" in result.smoke_artifacts
    # Registered with origin=generated (the machine-forged marker).
    entry = cat.get_entry("docx-maker")
    assert entry is not None
    assert entry.origin == "generated"
    # The skill persisted to config/skills/<name>/scripts/generate.py.
    script = Path(entry.skill_dir) / "scripts" / "generate.py"
    assert script.is_file()

    # Run the REGISTERED skill's script → a real, re-openable .docx artifact.
    from docx import Document

    workdir = tmp_path / "use"
    workdir.mkdir()
    res = await SubprocessSandbox(scratch_root=str(tmp_path)).run(
        ExecutionRequest(
            code=script.read_text(encoding="utf-8"),
            workdir=workdir,
            timeout_seconds=60,
        )
    )
    assert res.success, res.stderr
    out = workdir / "output.docx"
    assert out.is_file()
    assert out.read_bytes()[:2] == b"PK"  # docx is a zip archive
    reopened = Document(io.BytesIO(out.read_bytes()))
    texts = "\n".join(p.text for p in reopened.paragraphs)
    assert "Sample Report" in texts


async def test_forge_xlsx_skill(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM(_payload("xlsx-maker", _XLSX)), catalog=cat)
    result = await forge.forge(
        name="xlsx-maker", description="Create a spreadsheet.", task="produce an .xlsx",
    )
    assert result.success, result.errors
    assert "output.xlsx" in result.smoke_artifacts
    assert cat.get_entry("xlsx-maker") is not None


async def test_forge_csv_skill_stdlib_only(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM(_payload("csv-maker", _CSV)), catalog=cat)
    result = await forge.forge(
        name="csv-maker", description="Create a CSV.", task="produce a .csv",
    )
    assert result.success, result.errors
    assert "output.csv" in result.smoke_artifacts
    assert cat.get_entry("csv-maker") is not None


# ── honest-degrade: every failure leaves the catalog clean ─────────────────
async def test_forge_rejects_bad_frontmatter(tmp_path) -> None:
    payload = (
        "===FILE: SKILL.md===\n---\ndescription: no name here.\n---\n\n# X\n\n"
        "===FILE: scripts/generate.py===\n"
        'open("output.txt", "w").write("hi")\n'
    )
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM(payload), catalog=cat)
    result = await forge.forge(name="x", description="", task="")
    assert result.success is False
    assert cat.get_entry("x") is None


async def test_forge_rejects_script_syntax_error(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(
        llm_client=_FakeLLM(_payload("bad-syntax", "def broken(:\n    pass\n")),
        catalog=cat,
    )
    result = await forge.forge(name="bad-syntax", description="", task="")
    assert result.success is False
    assert any("syntax" in e.lower() for e in result.errors)
    assert cat.get_entry("bad-syntax") is None


async def test_forge_rejects_when_no_output_produced(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(
        llm_client=_FakeLLM(_payload("noop", 'print("did nothing")')), catalog=cat,
    )
    result = await forge.forge(name="noop", description="", task="")
    assert result.success is False
    assert any("smoke" in e.lower() or "deliverable" in e.lower() for e in result.errors)
    assert cat.get_entry("noop") is None


async def test_forge_rejects_forbidden_pattern(tmp_path) -> None:
    evil = 'eval("2 + 2")\nopen("output.txt", "w").write("x")\n'
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM(_payload("evil", evil)), catalog=cat)
    result = await forge.forge(name="evil", description="", task="")
    assert result.success is False
    assert any("forbidden" in e.lower() for e in result.errors)
    assert cat.get_entry("evil") is None


async def test_forge_rejects_empty_llm_output(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    forge = SkillForge(llm_client=_FakeLLM("", error="timeout"), catalog=cat)
    result = await forge.forge(name="x", description="", task="")
    assert result.success is False
    assert any("generation failed" in e.lower() for e in result.errors)
    assert cat.get_entry("x") is None


async def test_forge_rejects_duplicate_name(tmp_path) -> None:
    cat = await _catalog(tmp_path / "skills")
    first = await SkillForge(
        llm_client=_FakeLLM(_payload("dup", _CSV)), catalog=cat,
    ).forge(name="dup", description="", task="")
    assert first.success, first.errors
    # Forging the same name again hits the catalog duplicate guard.
    second = await SkillForge(
        llm_client=_FakeLLM(_payload("dup", _CSV)), catalog=cat,
    ).forge(name="dup", description="", task="")
    assert second.success is False
    assert any(
        "registration" in e.lower() or "exist" in e.lower() for e in second.errors
    )


async def test_forge_requires_name() -> None:
    forge = SkillForge(llm_client=_FakeLLM(""), catalog=object())
    result = await forge.forge(name="   ", description="", task="")
    assert result.success is False
    assert any("name" in e.lower() for e in result.errors)


# ── unit: parsing + path safety ────────────────────────────────────────────
def test_parse_files_extracts_blocks() -> None:
    raw = (
        "===FILE: SKILL.md===\nhello body\n"
        "===FILE: scripts/x.py===\nprint(1)\n"
    )
    files = SkillForge._parse_files(raw)
    assert files["SKILL.md"] == "hello body"
    assert files["scripts/x.py"] == "print(1)"


def test_parse_files_strips_outer_code_fence() -> None:
    raw = "```\n===FILE: SKILL.md===\nbody\n```"
    files = SkillForge._parse_files(raw)
    assert "SKILL.md" in files


def test_write_files_rejects_path_traversal(tmp_path) -> None:
    with pytest.raises(ValueError):
        SkillForge._write_files(tmp_path, {"../evil.py": "x"})
    with pytest.raises(ValueError):
        SkillForge._write_files(tmp_path, {"/etc/evil": "x"})
