"""Domain-partitioned configuration models (AD-1270e2).

``probos.config`` remains the permanent public facade. Import from there, not
from here; this package exists so ``config.py`` can stop being 7,842 lines.
"""

from __future__ import annotations

from probos.config_models.cognition import (
    AttentionConfig,
    DistillationConfig,
    DreamWMConfig,
    DreamingConfig,
    MemoryBudgetConfig,
    MetabolismConfig,
    PinnedKnowledgeConfig,
    ReconsolidationConfig,
    RetroactiveConfig,
    SelfModConfig,
    SpreadingActivationConfig,
    StorageGateConfig,
    TemporalValidityConfig,
    ThoughtStoreConfig,
    WorkingMemoryConfig,
)
from probos.config_models.core import (
    CircuitBreakerConfig,
    ConcurrencyConfig,
    ConsensusConfig,
    EventLogConfig,
    MeshConfig,
    PoolConfig,
    ScalingConfig,
    SystemInfo,
)
from probos.config_models.experience import (
    ApprovalInboxConfig,
    BaselineVRMManifest,
    CameraStreamConfig,
    DesktopConfig,
    DiscordConfig,
    GroupChatConfig,
    KnowledgeBrowserConfig,
    LipSyncConfig,
    OnboardingConfig,
    ScreenStreamConfig,
    SlackConfig,
    SpatialExplorerConfig,
    TTSConfig,
    WakeWordConfig,
    WebhookConfig,
    WorkstationsConfig,
)
from probos.config_models.integrations import (
    A2APeerConfig,
    AttachmentsConfig,
    BillConfig,
    CloudPickerProviderConfig,
    CommunicationBenchmarksConfig,
    CommunicationsConfig,
    CredentialVaultConfig,
    FederationArdConfig,
    FederationClusterMonitorConfig,
    FederationDiscoveryConfig,
    FederationMCPServerConfig,
    FederationPeerTrustConfig,
    FederationTLSConfig,
    HooksConfig,
    MCPAppHostConfig,
    MCPServerConfig,
    ObservabilityBridgeConfig,
    PacksConfig,
)

__all__ = [
    "A2APeerConfig",
    "ApprovalInboxConfig",
    "AttachmentsConfig",
    "AttentionConfig",
    "BaselineVRMManifest",
    "BillConfig",
    "CameraStreamConfig",
    "CircuitBreakerConfig",
    "CloudPickerProviderConfig",
    "CommunicationBenchmarksConfig",
    "CommunicationsConfig",
    "ConcurrencyConfig",
    "ConsensusConfig",
    "CredentialVaultConfig",
    "DesktopConfig",
    "DiscordConfig",
    "DistillationConfig",
    "DreamWMConfig",
    "DreamingConfig",
    "EventLogConfig",
    "FederationArdConfig",
    "FederationClusterMonitorConfig",
    "FederationDiscoveryConfig",
    "FederationMCPServerConfig",
    "FederationPeerTrustConfig",
    "FederationTLSConfig",
    "GroupChatConfig",
    "HooksConfig",
    "KnowledgeBrowserConfig",
    "LipSyncConfig",
    "MCPAppHostConfig",
    "MCPServerConfig",
    "MemoryBudgetConfig",
    "MeshConfig",
    "MetabolismConfig",
    "ObservabilityBridgeConfig",
    "OnboardingConfig",
    "PacksConfig",
    "PinnedKnowledgeConfig",
    "PoolConfig",
    "ReconsolidationConfig",
    "RetroactiveConfig",
    "ScalingConfig",
    "ScreenStreamConfig",
    "SelfModConfig",
    "SlackConfig",
    "SpatialExplorerConfig",
    "SpreadingActivationConfig",
    "StorageGateConfig",
    "SystemInfo",
    "TTSConfig",
    "TemporalValidityConfig",
    "ThoughtStoreConfig",
    "WakeWordConfig",
    "WebhookConfig",
    "WorkingMemoryConfig",
    "WorkstationsConfig",
]
